import java.awt.Color;
import java.awt.Font;
//import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.File;
import java.io.FileWriter;
import java.util.Scanner;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserConnection.java
 *
 * Created on 25 Jan, 2020, 4:24:08 PM
 */

/**
 *
 * @author Manas Trivedi
 */

/*

Sample program for testing: Adding two numbers

#include<stdio.h>
int main(){
    int t, a, b;
    scanf("%d", &t);
    while(t--){
        scanf("%d%d", &a, &b);
        printf("%d\n", a + b);
    }
    return 0;
}


*/
public class ChampionsArena extends javax.swing.JFrame {
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    String sql = null;
    String uid = null;
    String userToView = null;
    DefaultTableModel tm = null;
    DefaultTableModel tm2 = null;
    DefaultTableModel tm3 = null;
    DefaultTableModel tm4 = null;
    DefaultTableModel tm5 = null;
    DefaultTableModel tm6 = null;
    String currentProblemID = null;
    String cmd = null;
    int contestMode = 0; // 0 for solving old problems, 1 for solving particular previous contest's problems, 2 for solving current contest
    String contestID = null;
    
    ProcessBuilder processBuilder = new ProcessBuilder();

    /** Creates new form UserConnection */
    public ChampionsArena() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    String executeCommand(String cmd){
        try {
            System.out.println("Attempting to run command '" + cmd + "'...");
            processBuilder.command("bash", "-c", cmd);
            Process process = processBuilder.start();

            String output = "";

            BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
            String line;
            while ((line = reader.readLine()) != null) {
		output += line + "\n";
            }

            int exitVal = process.waitFor();
            if (exitVal == 0) {
		System.out.println("Success!");
		return output;
            }
            else {
		System.out.println("Something went wrong in executing the command.");
            }

        }
        catch (IOException e) {
            e.printStackTrace();
        }
        catch (InterruptedException e) {
            e.printStackTrace();
        }
        return "";
    }
    
    String readFromFile(String fileName) {
        try{
            File f1 = new File(fileName);
            Scanner scanner = new Scanner(f1);
            String data = "";
            while(scanner.hasNextLine()){
                data += scanner.nextLine() + " ";
            }
            scanner.close();
            return data;
        }
        catch (Exception e) {
            System.out.println("Error occurred in compilation step.");
            e.printStackTrace();
            return "";
        }
    }
    
    void writeToFile(String fileName, String data) {
        try{
            FileWriter fileWriter = new FileWriter(fileName);
            fileWriter.write(data);
            fileWriter.close();
            System.out.println("File written successfully");
        }
        catch(Exception e){
            System.out.println("Error occurred in writing to file.");
            e.printStackTrace();
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAccountFrame = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        createAccountButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        loginFrame = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        dashboard = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        searchFrame = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        requests = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton19 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        friendsFrame = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        profileFrame = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        profileActionButton = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        contestsFrame = new javax.swing.JFrame();
        jButton25 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        showCurrentContestsButton = new javax.swing.JButton();
        showPreviousContestsButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        problemsFrame = new javax.swing.JFrame();
        jButton27 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        standingsButton = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        solveProblemFrame = new javax.swing.JFrame();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        problemIDLabel = new javax.swing.JLabel();
        problemTitleLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        problemStatementTextArea = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        codeTextArea = new javax.swing.JTextArea();
        submitCodeButton = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        problemLevelLabel = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        standingsFrame = new javax.swing.JFrame();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        backToContestProblemsButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        signUpButton = new javax.swing.JButton();
        signInButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        createAccountFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        createAccountFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        createAccountFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                createAccountFrameWindowActivated(evt);
            }
        });
        createAccountFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(6, 41, 216));
        jLabel2.setText("Enter username:");
        createAccountFrame.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        createAccountFrame.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 360, 819, 50));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 41, 216));
        jLabel3.setText("Enter password:");
        createAccountFrame.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 464, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        createAccountFrame.getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 454, 819, 50));

        createAccountButton.setBackground(new java.awt.Color(132, 254, 245));
        createAccountButton.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        createAccountButton.setForeground(new java.awt.Color(6, 41, 216));
        createAccountButton.setText("Create Account");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });
        createAccountFrame.getContentPane().add(createAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 695, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(6, 41, 216));
        jLabel4.setText("Enter name:");
        createAccountFrame.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 276, -1, -1));

        jTextField2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        createAccountFrame.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 266, 819, 50));

        jButton1.setBackground(new java.awt.Color(132, 254, 245));
        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(6, 41, 216));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        createAccountFrame.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 100, 71));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(6, 41, 216));
        jLabel13.setText("Enter college:");
        createAccountFrame.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 559, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select college--" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        createAccountFrame.getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 548, 819, 50));

        jLabel29.setIcon(new javax.swing.ImageIcon("/home/manas/GitHub/Champions-Arena/Champions Arena/src/AbstractBlue.jpg")); // NOI18N
        createAccountFrame.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1840, 1060));

        loginFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        loginFrame.setBackground(new java.awt.Color(0, 184, 255));
        loginFrame.setForeground(new java.awt.Color(214, 49, 49));
        loginFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        loginFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                loginFrameWindowActivated(evt);
            }
        });
        loginFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(6, 41, 216));
        jLabel5.setText("Enter username:");
        loginFrame.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 410, 251, 49));

        jTextField3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        loginFrame.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 410, 567, 49));

        jPasswordField2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        loginFrame.getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 496, 567, 49));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(6, 41, 216));
        jLabel6.setText("Enter password:");
        loginFrame.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 496, 251, 49));

        loginButton.setBackground(new java.awt.Color(188, 248, 71));
        loginButton.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        loginButton.setForeground(new java.awt.Color(6, 41, 216));
        loginButton.setText("Login");
        loginButton.setActionCommand("<html><b>Login</b></html>");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginFrame.getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 681, 287, -1));

        jButton3.setBackground(new java.awt.Color(188, 248, 71));
        jButton3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(6, 41, 216));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        loginFrame.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, 100, 70));

        jLabel30.setIcon(new javax.swing.ImageIcon("/home/manas/GitHub/Champions-Arena/Champions Arena/src/AbstractColourful.jpg")); // NOI18N
        loginFrame.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -3, 1840, 1060));

        dashboard.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        dashboard.setMinimumSize(new java.awt.Dimension(1837, 1055));
        dashboard.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                dashboardWindowActivated(evt);
            }
        });
        dashboard.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(6, 41, 216));
        jLabel7.setText("Dashboard");
        dashboard.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, -1, -1));

        logoutButton.setBackground(new java.awt.Color(188, 248, 71));
        logoutButton.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(6, 41, 216));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        dashboard.getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 160, 165, 81));

        jButton7.setBackground(new java.awt.Color(188, 248, 71));
        jButton7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(6, 41, 216));
        jButton7.setText("Contests");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        dashboard.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 456, 205, 81));

        jButton8.setBackground(new java.awt.Color(188, 248, 71));
        jButton8.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(6, 41, 216));
        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        dashboard.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 456, 205, 81));

        jButton13.setBackground(new java.awt.Color(188, 248, 71));
        jButton13.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(6, 41, 216));
        jButton13.setText("Requests");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        dashboard.getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1073, 456, 205, 81));

        jButton16.setBackground(new java.awt.Color(188, 248, 71));
        jButton16.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton16.setForeground(new java.awt.Color(6, 41, 216));
        jButton16.setText("Friends");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        dashboard.getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1357, 456, 205, 81));

        jButton21.setBackground(new java.awt.Color(188, 248, 71));
        jButton21.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton21.setForeground(new java.awt.Color(6, 41, 216));
        jButton21.setText("Problems");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        dashboard.getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 456, 205, 81));

        jButton24.setBackground(new java.awt.Color(188, 248, 71));
        jButton24.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton24.setForeground(new java.awt.Color(6, 41, 216));
        jButton24.setText("Your profile");
        jButton24.setToolTipText("Go to your profile");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        dashboard.getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1432, 160, 166, 81));

        jLabel31.setIcon(new javax.swing.ImageIcon("/home/manas/GitHub/Champions-Arena/Champions Arena/src/AbstractSquare.jpg")); // NOI18N
        dashboard.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1840, 1060));

        searchFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        searchFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        searchFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                searchFrameWindowActivated(evt);
            }
        });
        searchFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 25, 255));
        jLabel8.setText("Search users based on:");
        searchFrame.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 53, -1, -1));

        jButton9.setBackground(new java.awt.Color(238, 47, 204));
        jButton9.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 25, 255));
        jButton9.setText("Search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        searchFrame.getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 429, 280, 70));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 25, 255));
        jLabel9.setText("User name:");
        searchFrame.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 150, -1, -1));

        jTextField4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        searchFrame.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 140, 788, 50));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 25, 255));
        jLabel10.setText("College name:");
        searchFrame.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 321, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        searchFrame.getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 310, 788, 50));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 25, 255));
        jLabel11.setText("Name:");
        searchFrame.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 235, -1, -1));

        jTextField5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        searchFrame.getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 225, 788, 50));

        jTable1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User name", "Name", "College"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(30);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        searchFrame.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 552, 1700, 420));

        jButton12.setBackground(new java.awt.Color(238, 47, 204));
        jButton12.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 25, 255));
        jButton12.setText("Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        searchFrame.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 100, 70));

        jLabel32.setIcon(new javax.swing.ImageIcon("/home/manas/GitHub/Champions-Arena/Champions Arena/src/AbstractLightPurple.jpg")); // NOI18N
        searchFrame.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1840, 1030));

        requests.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        requests.setMinimumSize(new java.awt.Dimension(1837, 1055));
        requests.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                requestsWindowActivated(evt);
            }
        });
        requests.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User name", "Name", "College"
            }
        ));
        jTable2.setRowHeight(30);
        jTable2.setShowHorizontalLines(false);
        jTable2.setShowVerticalLines(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        requests.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 196, 1308, 660));

        jButton19.setBackground(new java.awt.Color(255, 178, 0));
        jButton19.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton19.setForeground(new java.awt.Color(113, 2, 208));
        jButton19.setText("Back");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        requests.getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 100, 70));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(113, 2, 208));
        jLabel12.setText("Connection Requests");
        requests.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 100, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon("/home/manas/GitHub/Champions-Arena/Champions Arena/src/AbstractYellow.jpg")); // NOI18N
        requests.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1840, 1060));

        friendsFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        friendsFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        friendsFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                friendsFrameWindowActivated(evt);
            }
        });
        friendsFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User name", "Name", "College"
            }
        ));
        jTable3.setRowHeight(30);
        jTable3.setShowHorizontalLines(false);
        jTable3.setShowVerticalLines(false);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        friendsFrame.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 1306, 620));

        jButton17.setBackground(new java.awt.Color(243, 244, 2));
        jButton17.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton17.setForeground(new java.awt.Color(200, 1, 65));
        jButton17.setText("Back");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        friendsFrame.getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 100, 70));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(200, 1, 65));
        jLabel14.setText("Friends");
        friendsFrame.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon("/home/manas/GitHub/Champions-Arena/Champions Arena/src/YellowGradient.png")); // NOI18N
        friendsFrame.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1840, 1020));

        profileFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        profileFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        profileFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                profileFrameWindowActivated(evt);
            }
        });
        profileFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(136, 0, 210));
        jLabel17.setText("Username:");
        profileFrame.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 310, -1, -1));

        jLabel18.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(136, 0, 210));
        jLabel18.setText("<username>");
        profileFrame.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(967, 310, 730, -1));

        jLabel19.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(136, 0, 210));
        jLabel19.setText("Name:");
        profileFrame.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 412, -1, -1));

        jLabel20.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(136, 0, 210));
        jLabel20.setText("<name>");
        profileFrame.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(967, 412, 730, -1));

        jLabel21.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(136, 0, 210));
        jLabel21.setText("College:");
        profileFrame.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 515, -1, -1));

        jLabel22.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(136, 0, 210));
        jLabel22.setText("<college>");
        profileFrame.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(967, 515, 730, -1));

        jButton22.setBackground(new java.awt.Color(200, 254, 67));
        jButton22.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton22.setForeground(new java.awt.Color(136, 0, 210));
        jButton22.setText("Back");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        profileFrame.getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 100, 70));

        profileActionButton.setBackground(new java.awt.Color(200, 254, 67));
        profileActionButton.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        profileActionButton.setForeground(new java.awt.Color(136, 0, 210));
        profileActionButton.setText("Profile Action");
        profileActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionButtonActionPerformed(evt);
            }
        });
        profileFrame.getContentPane().add(profileActionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(844, 663, -1, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon("/home/manas/GitHub/Champions-Arena/Champions Arena/src/LightGreen.jpg")); // NOI18N
        profileFrame.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1840, 1060));

        contestsFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        contestsFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        contestsFrame.setPreferredSize(new java.awt.Dimension(1837, 1055));
        contestsFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                contestsFrameWindowActivated(evt);
            }
        });
        contestsFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton25.setBackground(new java.awt.Color(108, 61, 14));
        jButton25.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton25.setForeground(new java.awt.Color(248, 176, 17));
        jButton25.setText("Back");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        contestsFrame.getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 100, 70));

        jTable5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Name", "Start", "End"
            }
        ));
        jTable5.setRowHeight(30);
        jTable5.setShowHorizontalLines(false);
        jTable5.setShowVerticalLines(false);
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable5);

        contestsFrame.getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 1319, 534));

        showCurrentContestsButton.setBackground(new java.awt.Color(108, 61, 14));
        showCurrentContestsButton.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        showCurrentContestsButton.setForeground(new java.awt.Color(248, 176, 17));
        showCurrentContestsButton.setText("Current Contests");
        showCurrentContestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCurrentContestsButtonActionPerformed(evt);
            }
        });
        contestsFrame.getContentPane().add(showCurrentContestsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, -1, -1));

        showPreviousContestsButton.setBackground(new java.awt.Color(108, 61, 14));
        showPreviousContestsButton.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        showPreviousContestsButton.setForeground(new java.awt.Color(248, 176, 17));
        showPreviousContestsButton.setText("Past Contests");
        showPreviousContestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPreviousContestsButtonActionPerformed(evt);
            }
        });
        contestsFrame.getContentPane().add(showPreviousContestsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 220, 215, -1));

        jLabel16.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(248, 176, 17));
        jLabel16.setText("Contests");
        contestsFrame.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, -1, -1));

        jLabel40.setBackground(new java.awt.Color(108, 61, 14));
        jLabel40.setIcon(new javax.swing.ImageIcon("/home/manas/GitHub/Champions-Arena/Champions Arena/src/Energy.jpg")); // NOI18N
        contestsFrame.getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1840, 1060));

        problemsFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        problemsFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        problemsFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                problemsFrameWindowActivated(evt);
            }
        });
        problemsFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton27.setBackground(new java.awt.Color(67, 112, 228));
        jButton27.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton27.setForeground(new java.awt.Color(254, 250, 17));
        jButton27.setText("Back");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        problemsFrame.getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 100, 70));

        jTable4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Level"
            }
        ));
        jTable4.setRowHeight(30);
        jTable4.setShowHorizontalLines(false);
        jTable4.setShowVerticalLines(false);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        problemsFrame.getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 208, 1023, 554));

        standingsButton.setBackground(new java.awt.Color(67, 112, 228));
        standingsButton.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        standingsButton.setForeground(new java.awt.Color(254, 250, 17));
        standingsButton.setText("Standings");
        standingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standingsButtonActionPerformed(evt);
            }
        });
        problemsFrame.getContentPane().add(standingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1173, 99, 274, 72));

        jLabel23.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(254, 250, 17));
        jLabel23.setText("Problem Set");
        problemsFrame.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));
        problemsFrame.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 38, 130, 30));

        jLabel39.setIcon(new javax.swing.ImageIcon("/home/manas/GitHub/Champions-Arena/Champions Arena/src/Lightning.jpg")); // NOI18N
        problemsFrame.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1840, 1060));

        solveProblemFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        solveProblemFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        solveProblemFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                solveProblemFrameWindowActivated(evt);
            }
        });
        solveProblemFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(254, 254, 254));
        jLabel25.setText("Problem ID:");
        solveProblemFrame.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 154, -1, -1));

        jLabel26.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(254, 254, 254));
        jLabel26.setText("Title:");
        solveProblemFrame.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 241, -1, -1));

        problemIDLabel.setBackground(new java.awt.Color(62, 62, 62));
        problemIDLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        problemIDLabel.setForeground(new java.awt.Color(254, 254, 254));
        problemIDLabel.setOpaque(true);
        solveProblemFrame.getContentPane().add(problemIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 154, 111, 29));

        problemTitleLabel.setBackground(new java.awt.Color(62, 62, 62));
        problemTitleLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        problemTitleLabel.setForeground(new java.awt.Color(254, 254, 254));
        problemTitleLabel.setOpaque(true);
        solveProblemFrame.getContentPane().add(problemTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 241, 1216, 29));

        problemStatementTextArea.setEditable(false);
        problemStatementTextArea.setBackground(new java.awt.Color(62, 62, 62));
        problemStatementTextArea.setColumns(20);
        problemStatementTextArea.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        problemStatementTextArea.setForeground(new java.awt.Color(254, 254, 254));
        problemStatementTextArea.setLineWrap(true);
        problemStatementTextArea.setRows(5);
        problemStatementTextArea.setWrapStyleWord(true);
        jScrollPane5.setViewportView(problemStatementTextArea);

        solveProblemFrame.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 328, 1363, -1));

        jLabel27.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(254, 254, 254));
        jLabel27.setText("Enter your code here:");
        solveProblemFrame.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 541, -1, -1));

        codeTextArea.setBackground(new java.awt.Color(62, 62, 62));
        codeTextArea.setColumns(20);
        codeTextArea.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        codeTextArea.setForeground(new java.awt.Color(254, 254, 254));
        codeTextArea.setRows(5);
        codeTextArea.setText(" #include <stdio.h>\nint main() {\n        // your code here\n}\n");
        jScrollPane6.setViewportView(codeTextArea);

        solveProblemFrame.getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 602, 1363, 303));

        submitCodeButton.setBackground(new java.awt.Color(1, 1, 1));
        submitCodeButton.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        submitCodeButton.setForeground(new java.awt.Color(254, 254, 254));
        submitCodeButton.setText("Submit Code");
        submitCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCodeButtonActionPerformed(evt);
            }
        });
        solveProblemFrame.getContentPane().add(submitCodeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 963, 206, 75));

        jLabel28.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(254, 254, 254));
        jLabel28.setText("Level:");
        solveProblemFrame.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 154, -1, -1));

        problemLevelLabel.setBackground(new java.awt.Color(62, 62, 62));
        problemLevelLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        problemLevelLabel.setForeground(new java.awt.Color(254, 254, 254));
        problemLevelLabel.setOpaque(true);
        solveProblemFrame.getContentPane().add(problemLevelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 154, 79, 29));

        jButton29.setBackground(new java.awt.Color(1, 1, 1));
        jButton29.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton29.setForeground(new java.awt.Color(254, 254, 254));
        jButton29.setText("Back");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        solveProblemFrame.getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 100, 70));

        jLabel35.setIcon(new javax.swing.ImageIcon("/home/manas/GitHub/Champions-Arena/Champions Arena/src/AbstractDarkGrey.jpg")); // NOI18N
        solveProblemFrame.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1840, 1070));

        standingsFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        standingsFrame.setMinimumSize(new java.awt.Dimension(1837, 1055));
        standingsFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                standingsFrameWindowActivated(evt);
            }
        });
        standingsFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "A", "B", "C"
            }
        ));
        jTable6.setRowHeight(30);
        jTable6.setShowHorizontalLines(false);
        jTable6.setShowVerticalLines(false);
        jTable6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable6MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jTable6);

        standingsFrame.getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 316, 1337, 539));

        backToContestProblemsButton.setBackground(new java.awt.Color(179, 179, 179));
        backToContestProblemsButton.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        backToContestProblemsButton.setForeground(new java.awt.Color(1, 1, 1));
        backToContestProblemsButton.setText("Back");
        backToContestProblemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToContestProblemsButtonActionPerformed(evt);
            }
        });
        standingsFrame.getContentPane().add(backToContestProblemsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 100, 70));

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(254, 254, 254));
        jLabel15.setText("Standings - R1");
        standingsFrame.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon("/home/manas/GitHub/Champions-Arena/Champions Arena/src/BlackDesigner.jpg")); // NOI18N
        standingsFrame.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -2, 1860, 1060));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1837, 1055));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUpButton.setBackground(new java.awt.Color(246, 216, 28));
        signUpButton.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(0, 111, 222));
        signUpButton.setText("Register");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 626, 230, 70));

        signInButton.setBackground(new java.awt.Color(246, 216, 28));
        signInButton.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        signInButton.setForeground(new java.awt.Color(0, 111, 222));
        signInButton.setText("Login");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        getContentPane().add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 626, 230, 70));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 111, 222));
        jLabel1.setText("Welcome to Champions Arena!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon("/home/manas/GitHub/Champions-Arena/Champions Arena/src/AbstractOrange.jpg")); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1840, 1040));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        createAccountFrame.setVisible(true);
        this.dispose();
}//GEN-LAST:event_signUpButtonActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        loginFrame.setVisible(true);
        this.dispose();
}//GEN-LAST:event_signInButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //ImageIcon icon = new ImageIcon("/BackButton.png");
        //this.setIconImage(icon.getImage());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/cparena", "root", "1234");
            stmt = con.createStatement();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowActivated

    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        try{
            String college = (String)jComboBox2.getSelectedItem();
            System.out.println("College obtained from jComboBox2 is: " + college);
            System.out.println("jComboBox2.getSelectedIndex() gives: " + jComboBox2.getSelectedIndex());
            if(jComboBox2.getSelectedIndex()==0 || jComboBox2.getSelectedIndex()==-1){
                college = JOptionPane.showInputDialog(null, "College not on the list?\nEnter the name of your college here:");
                System.out.println("College obtained from JOptionPane is: " + college);
            }
            System.out.println("Flag3");
            if(college == null || college.equals("")){
                JOptionPane.showMessageDialog(null, "Please enter name of college to create account.");
            }
            else{
                sql = "INSERT INTO USER VALUES('" + jTextField1.getText() + "', '" + jTextField2.getText() + "', '" + jPasswordField1.getText() + "', '" + college + "');";
                System.out.println(sql);
                jTextField1.setText("");
                jTextField2.setText("");
                jPasswordField1.setText("");
                jComboBox2.setSelectedItem("--Select college--");
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Account created successfully.");
                createAccountFrame.dispose();
                this.setVisible(true);
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage()+" This username is already taken.\nTry another one!");
        }
}//GEN-LAST:event_createAccountButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        jPasswordField1.requestFocus();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        jTextField1.requestFocus();
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        jComboBox2.requestFocus();
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        try{
            uid = jTextField3.getText();
            String passwd = new String(jPasswordField2.getPassword());
            //System.out.println(passwd);
            sql = "SELECT * FROM USER WHERE uid = '" + uid + "';";
            System.out.println(sql);
            rs = stmt.executeQuery(sql);
            rs.first();
            //System.out.println(rs.getString("passwd"));
            if(passwd.equals(rs.getString("passwd"))){
                jTextField3.setText("");
                jPasswordField2.setText("");
                dashboard.setVisible(true);
                loginFrame.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Incorrect password.\nPlease try again.");
                jPasswordField2.setText("");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
}//GEN-LAST:event_loginButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        jPasswordField2.requestFocus();
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        try{
            uid = jTextField3.getText();
            String passwd = jPasswordField2.getText();
            //System.out.println(passwd);
            sql = "SELECT * FROM USER WHERE uid = '" + uid + "';";
            System.out.println(sql);
            rs = stmt.executeQuery(sql);
            rs.first();
            //System.out.println(rs.getString("passwd"));
            if(passwd.equals(rs.getString("passwd"))){
                jTextField3.setText("");
                jPasswordField2.setText("");
                dashboard.setVisible(true);
                loginFrame.dispose();
            }
            else{
                System.out.println("Incorrect password.\nPlease try again.");
                jPasswordField2.setText("");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextField2.setText("");
        jTextField1.setText("");
        jPasswordField1.setText("");
        createAccountFrame.dispose();
        this.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField3.setText("");
        jPasswordField2.setText("");
        loginFrame.dispose();
        this.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        uid = null;
        dashboard.dispose();
        loginFrame.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        dashboard.dispose();
        searchFrame.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try{
            tm.setRowCount(0);
            String username = jTextField4.getText();
            String name = jTextField5.getText();
            String college = (String)jComboBox1.getSelectedItem();
            if(username.equals("") && name.equals("") && college.equals("--Select college--"))
                sql = "SELECT * FROM USER;";
            else if(username.equals("") && name.equals(""))
                sql = "SELECT * FROM USER WHERE college = '" + college + "' ORDER BY uname ASC;";
            else if(username.equals("") && college.equals("--Select college--"))
                sql = "SELECT * FROM USER WHERE uname LIKE '%" + name + "%' ORDER BY uname ASC;";
            else if(name.equals("") && college.equals("--Select college--"))
                sql = "SELECT * FROM USER WHERE uid = '" + username + "' ORDER BY uname ASC;";
            else if(college.equals("--Select college--"))
                sql = "SELECT * FROM USER WHERE uid = '" + username + "' AND uname LIKE '%" + name + "%' ORDER BY uname ASC;";
            else if(name.equals(""))
                sql = "SELECT * FROM USER WHERE uid = '" + username + "' AND college = '" + college + "' ORDER BY uname ASC;";
            else if(username.equals(""))
                sql = "SELECT * FROM USER WHERE uname LIKE '%" + name + "%' AND college = '" + college + "' ORDER BY uname ASC;";
            else
                sql = "SELECT * FROM USER WHERE uid = '" + username + "' AND uname LIKE '%" + name + "%' AND college = '" + college + "' ORDER BY uname ASC;";
            System.out.println(sql);
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                if( ! uid.equals(rs.getString("uid"))){
                    tm.addRow(new Object [] {rs.getString("uid"), rs.getString("uname"), rs.getString("college")});
                }
            }
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        contestsFrame.setVisible(true);
        dashboard.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void searchFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_searchFrameWindowActivated
        jTable1.getTableHeader().setFont(new Font("Ubuntu", Font.PLAIN, 24));
        try{
            tm = (DefaultTableModel)jTable1.getModel();
            tm.setRowCount(0);
            jComboBox1.removeAllItems();
            jComboBox1.addItem("--Select college--");
            sql = "SELECT DISTINCT college FROM USER ORDER BY college ASC;";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                System.out.println("rs.getString(\"college\") gives "+ rs.getString("college"));
                jComboBox1.addItem(rs.getString("college"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
}//GEN-LAST:event_searchFrameWindowActivated

    private void createAccountFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_createAccountFrameWindowActivated
        //jButton1.setIcon(new ImageIcon(ChampionsArena.class.getResource("BackButton.png")));
        try{
            //System.out.println("Flag 1");
            jComboBox2.removeAllItems();
            jComboBox2.addItem("--Select college--");
            sql = "SELECT DISTINCT college FROM USER ORDER BY college ASC;";
            rs = stmt.executeQuery(sql);
            System.out.println("Flag 2");
            while(rs.next()){
                //System.out.println("rs.getString(\"college\") gives "+ rs.getString("college"));
                jComboBox2.addItem(rs.getString("college"));
                //System.out.println("Flag 3");
            }
            jComboBox2.setSelectedItem("--Select college--");
            jTextField2.requestFocus();
            //System.out.println(jComboBox1.getSelectedIndex());
            //System.out.println("Flag3");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_createAccountFrameWindowActivated

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jTextField4.setText("");
        jTextField5.setText("");
        tm.setRowCount(0);
        searchFrame.dispose();
        dashboard.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        requests.setVisible(true);
        dashboard.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void requestsWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_requestsWindowActivated
        jTable2.getTableHeader().setFont(new Font("Ubuntu", Font.PLAIN, 24));
        try{
            tm2 = (DefaultTableModel)jTable2.getModel();
            tm2.setRowCount(0);
            sql = "SELECT * FROM USER WHERE uid IN(SELECT user1 FROM CONNECTION WHERE user2 = '" + uid + "' AND status = 0);";
            System.out.println(sql);
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                tm2.addRow(new Object [] {rs.getString("uid"), rs.getString("uname"), rs.getString("college")});
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_requestsWindowActivated

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        friendsFrame.setVisible(true);
        dashboard.dispose();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        tm3.setRowCount(0);
        dashboard.setVisible(true);
        friendsFrame.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void friendsFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_friendsFrameWindowActivated
        jTable3.getTableHeader().setFont(new Font("Ubuntu", Font.PLAIN, 24));
        try{
            tm3 = (DefaultTableModel)jTable3.getModel();
            tm3.setRowCount(0);
            sql = "SELECT * FROM USER WHERE uid IN(SELECT user1 FROM CONNECTION WHERE user2 = '" + uid + "' AND status = 1 UNION SELECT user2 FROM CONNECTION WHERE user1 = '" + uid + "' AND status = 1);"; // NEEDS TO BE A TABLE JOIN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                tm3.addRow(new Object [] {rs.getString("uid"), rs.getString("uname"), rs.getString("college")});
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_friendsFrameWindowActivated

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        tm2.setRowCount(0);
        dashboard.setVisible(true);
        requests.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void dashboardWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dashboardWindowActivated
        // jButton24.setText(uid);
    }//GEN-LAST:event_dashboardWindowActivated

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        userToView = uid;
        profileFrame.setVisible(true);
        dashboard.dispose();
    }//GEN-LAST:event_jButton24ActionPerformed

    private void profileFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_profileFrameWindowActivated
        profileActionButton.setVisible(false);
        try{
            sql = "SELECT * FROM USER WHERE uid = '" + userToView + "';";
            rs = stmt.executeQuery(sql);
            rs.first();
            jLabel18.setText(rs.getString("uid"));
            jLabel20.setText(rs.getString("uname"));
            jLabel22.setText(rs.getString("college"));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        if(userToView.equals(uid)){
            return;
        }
        try{
            sql= "SELECT * FROM CONNECTION WHERE user1 = '" + userToView + "' AND user2 = '" + uid + "' OR user1 = '" + uid + "' AND user2 = '" + userToView + "';";
            rs = stmt.executeQuery(sql);
            if(! rs.next()){
                profileActionButton.setVisible(true);
                profileActionButton.setText("Send Request");
                return;
            }
            if(rs.getInt("status") == 1){
                return;
            }
            else{
                if(rs.getString("user1").equals(uid)){
                    profileActionButton.setVisible(true);
                    profileActionButton.setText("Unsend Request");
                }
                else{
                    profileActionButton.setVisible(true);
                    profileActionButton.setText("Accept Request");
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_profileFrameWindowActivated

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        profileFrame.dispose();
        dashboard.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        problemsFrame.setVisible(true);
        dashboard.dispose();
        contestMode = 0;
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        dashboard.setVisible(true);
        tm5.setRowCount(0);
        contestsFrame.dispose();
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        dashboard.setVisible(true);
        problemsFrame.dispose();
    }//GEN-LAST:event_jButton27ActionPerformed

    private void problemsFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_problemsFrameWindowActivated
        jTable4.getTableHeader().setFont(new Font("Ubuntu", Font.PLAIN, 24));
        try{
            tm4 = (DefaultTableModel)jTable4.getModel();
            tm4.setRowCount(0);
            if(contestMode == 0){ // User is here just to solve problems
                standingsButton.setVisible(false);
                jLabel23.setText("Problem Set");
                sql = "SELECT * FROM PROBLEM WHERE ContestID IN(SELECT ID FROM CONTEST WHERE End < now());";
                rs = stmt.executeQuery(sql);
                while(rs.next()){
                    tm4.addRow(new Object [] {rs.getString("ID"), rs.getString("Title"), rs.getString("Level")});
                }
            }
            else if(contestMode == 1){ // User is here to give previous contest, not current
                standingsButton.setVisible(true);
                standingsButton.setText("Final standings");
                jLabel23.setText("Problems - " + contestID);
                sql = "SELECT * FROM PROBLEM WHERE ContestID = '" + contestID + "';";
                rs = stmt.executeQuery(sql);
                while(rs.next()){
                    tm4.addRow(new Object [] {rs.getString("ID"), rs.getString("Title"),rs.getString("Level")});
                }
            }
            else{ // User is here to give a current contest!
                standingsButton.setVisible(true);
                standingsButton.setText("Current standings");
                jLabel23.setText("Problems - " + contestID);
                sql = "SELECT * FROM PROBLEM WHERE ContestID = '" + contestID + "';";
                rs = stmt.executeQuery(sql);
                while(rs.next()){
                    tm4.addRow(new Object [] {rs.getString("ID"), rs.getString("Title"),"?"});
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_problemsFrameWindowActivated

    private void solveProblemFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_solveProblemFrameWindowActivated
        codeTextArea.setCaretColor(Color.white);
        try{
            sql = "SELECT * FROM PROBLEM WHERE ID = '" + currentProblemID + "';";
            rs = stmt.executeQuery(sql);
            rs.first();
            problemIDLabel.setText(rs.getString("ID"));
            if(contestMode == 2){
                problemLevelLabel.setText("?");
            }
            else{
                problemLevelLabel.setText("" + rs.getInt("Level"));
            }
            problemTitleLabel.setText(rs.getString("Title"));
            problemStatementTextArea.setText(rs.getString("Statement"));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_solveProblemFrameWindowActivated

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        currentProblemID = (String)tm4.getValueAt(jTable4.getSelectedRow(), 0);
        solveProblemFrame.setVisible(true);
        problemsFrame.dispose();
    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        problemIDLabel.setText("");
        problemLevelLabel.setText("");
        problemTitleLabel.setText("");
        problemStatementTextArea.setText("");
        codeTextArea.setText("");
        solveProblemFrame.dispose();
        problemsFrame.setVisible(true);
    }//GEN-LAST:event_jButton29ActionPerformed

    private void submitCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitCodeButtonActionPerformed
        
        String userCode = codeTextArea.getText();
        int answerIsCorrect = 1;
        
        writeToFile("userCode.c", userCode);

        cmd = "gcc userCode.c &> compilationOutput.txt";
        executeCommand(cmd);
        
        String data = readFromFile("compilationOutput.txt");
        if(data.contains("error")){
            answerIsCorrect = 0;
            JOptionPane.showMessageDialog(null, "Compilation error.");
            cmd = "rm -f compilationOutput.txt userCode.c";
            executeCommand(cmd);
        }
        else{
            System.out.println("Compiled successfully.");
        
            try{
                sql = "SELECT * FROM TESTCASE WHERE ID = '" + currentProblemID + "';";
                rs = stmt.executeQuery(sql);
                while(rs.next()){
                    String inputData = (String)rs.getString("Input");
                    writeToFile("inputFile.txt", inputData);
                    String expectedOutput = (String)rs.getString("ExpectedOutput");
                    writeToFile("expectedOutput.txt", expectedOutput);
                
                    cmd = "./a.out < inputFile.txt > outputFile.txt";
                    executeCommand(cmd);
        
                    cmd = "diff outputFile.txt expectedOutput.txt &> compareOutputs.txt";
                    executeCommand(cmd);
        
                    data = readFromFile("compareOutputs.txt");
                    if( ! data.equals("")){
                        answerIsCorrect = 0;
                    }
                }
                if(answerIsCorrect == 1){
                    JOptionPane.showMessageDialog(null, "Correct answer!");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Wrong answer. Try again!");
                }
            
                cmd = "rm -f a.out compareOutputs.txt compilationOutput.txt expectedOutput.txt userCode.c inputFile.txt outputFile.txt";
                executeCommand(cmd);
            
            
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        
        try{
            if(contestMode == 2){
                sql= "SELECT * FROM SUBMISSION WHERE uid = '" + uid + "' AND ContestID = '" + contestID + "';";
                rs = stmt.executeQuery(sql);
                if(! rs.next()){
                    sql = "INSERT INTO SUBMISSION VALUES('" + uid + "', '" + contestID + "', 0, 0, 0);";
                    stmt.executeUpdate(sql);
                    sql = "UPDATE SUBMISSION SET " + currentProblemID.substring(1, 2) + " = " + answerIsCorrect + " WHERE uid = '" + uid + "' AND ContestID = '" + contestID + "';";
                    stmt.executeUpdate(sql);
                }
                else{
                    if(rs.getInt(currentProblemID.substring(1, 2)) == 0){
                        sql = "UPDATE SUBMISSION SET " + currentProblemID.charAt(1) + " = " + answerIsCorrect + " WHERE uid = '" + uid + "' AND ContestID = '" + contestID + "';";
                        stmt.executeUpdate(sql);
                    }
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_submitCodeButtonActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        userToView = (String)tm3.getValueAt(jTable3.getSelectedRow(), 0);
        profileFrame.setVisible(true);
        friendsFrame.dispose();
        tm3.setRowCount(0);
    }//GEN-LAST:event_jTable3MouseClicked

    private void contestsFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_contestsFrameWindowActivated
        jTable5.getTableHeader().setFont(new Font("Ubuntu", Font.PLAIN, 24));
        try{
            contestMode = 2;
            tm5 = (DefaultTableModel)jTable5.getModel();
            tm5.setRowCount(0);
            sql = "SELECT * FROM CONTEST WHERE Start <= now() AND End >= now();";
            // sql = "SELECT * FROM CONTEST WHERE Start <= now();";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                tm5.addRow(new Object [] {rs.getString("ID"), rs.getString("Name"), rs.getString("Start"), rs.getString("End")});
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_contestsFrameWindowActivated

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        contestID = (String)tm5.getValueAt(jTable5.getSelectedRow(), 0);
        contestsFrame.dispose();
        tm5.setRowCount(0);
        problemsFrame.setVisible(true);
    }//GEN-LAST:event_jTable5MouseClicked

    private void showCurrentContestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCurrentContestsButtonActionPerformed
        try{
            contestMode = 2;
            tm5.setRowCount(0);
            sql = "SELECT * FROM CONTEST WHERE Start <= now() AND End >= now();";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                tm5.addRow(new Object [] {rs.getString("ID"), rs.getString("Name"), rs.getString("Start"), rs.getString("End")});
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_showCurrentContestsButtonActionPerformed

    private void showPreviousContestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPreviousContestsButtonActionPerformed
        try{
            contestMode = 1;
            tm5.setRowCount(0);
            sql = "SELECT * FROM CONTEST WHERE End < now();";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                tm5.addRow(new Object [] {rs.getString("ID"), rs.getString("Name"), rs.getString("Start"), rs.getString("End")});
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_showPreviousContestsButtonActionPerformed

    private void standingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standingsButtonActionPerformed
        standingsFrame.setVisible(true);
        problemsFrame.dispose();
    }//GEN-LAST:event_standingsButtonActionPerformed

    private void standingsFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_standingsFrameWindowActivated
        jTable6.getTableHeader().setFont(new Font("Ubuntu", Font.PLAIN, 24));
        jLabel15.setText("Standings - " + contestID);
        tm6 = (DefaultTableModel)jTable6.getModel();
        tm6.setRowCount(0);
        try{
            sql= "SELECT * FROM SUBMISSION WHERE ContestID = '" + contestID + "' AND A = 1 AND B = 1 AND C = 1;";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                tm6.addRow(new Object [] {rs.getString("uid"), rs.getInt("A"), rs.getInt("B"), rs.getInt("C")});
            }
            sql= "SELECT * FROM SUBMISSION WHERE ContestID = '" + contestID + "' AND ((A = 1 AND B = 1 AND C = 0) OR (A = 0 AND B = 1 AND C = 1) or (A = 1 AND B = 0 AND C = 1));";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                tm6.addRow(new Object [] {rs.getString("uid"), rs.getInt("A"), rs.getInt("B"), rs.getInt("C")});
            }
            sql= "SELECT * FROM SUBMISSION WHERE ContestID = '" + contestID + "' AND ((A = 1 AND B = 0 AND C = 0) OR (A = 0 AND B = 1 AND C = 0) or (A = 0 AND B = 0 AND C = 1));";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                tm6.addRow(new Object [] {rs.getString("uid"), rs.getInt("A"), rs.getInt("B"), rs.getInt("C")});
            }
            sql= "SELECT * FROM SUBMISSION WHERE ContestID = '" + contestID + "' AND A = 0 AND B = 0 AND C = 0;";
            rs = stmt.executeQuery(sql);
            while(rs.next()){
                tm6.addRow(new Object [] {rs.getString("uid"), rs.getInt("A"), rs.getInt("B"), rs.getInt("C")});
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_standingsFrameWindowActivated

    private void backToContestProblemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToContestProblemsButtonActionPerformed
        problemsFrame.setVisible(true);
        standingsFrame.dispose();
    }//GEN-LAST:event_backToContestProblemsButtonActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        userToView = (String)tm2.getValueAt(jTable2.getSelectedRow(), 0);
        profileFrame.setVisible(true);
        requests.dispose();
        tm2.setRowCount(0);
    }//GEN-LAST:event_jTable2MouseClicked

    private void profileActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionButtonActionPerformed
        try{
            String profileActionText = profileActionButton.getText();
            if(profileActionText.equals("Send Request")){
                sql = "INSERT INTO CONNECTION VALUES('" + uid + "', '" + userToView + "', 0);";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Request sent!");
            }
            else if(profileActionText.equals("Accept Request")){
                sql = "UPDATE CONNECTION SET status = 1 WHERE user1 = '" + userToView + "' AND user2 = '" + uid + "';";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Request accepted!");
            }
            else if(profileActionText.equals("Unsend Request")){
                sql = "DELETE FROM CONNECTION WHERE user1 = '" + uid + "' AND user2 = '" + userToView + "' AND status = 0;";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Request unsent.");
            }
            else{
                return;
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_profileActionButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        userToView = (String)tm.getValueAt(jTable1.getSelectedRow(), 0);
        profileFrame.setVisible(true);
        searchFrame.dispose();
        tm.setRowCount(0);
        jTextField4.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable6MouseClicked
        userToView = (String)tm6.getValueAt(jTable6.getSelectedRow(), 0);
        profileFrame.setVisible(true);
        standingsFrame.dispose();
        tm6.setRowCount(0);
    }//GEN-LAST:event_jTable6MouseClicked

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void loginFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loginFrameWindowActivated
        jTextField3.requestFocus();
    }//GEN-LAST:event_loginFrameWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChampionsArena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToContestProblemsButton;
    private javax.swing.JTextArea codeTextArea;
    private javax.swing.JFrame contestsFrame;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JFrame createAccountFrame;
    private javax.swing.JFrame dashboard;
    private javax.swing.JFrame friendsFrame;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton loginButton;
    private javax.swing.JFrame loginFrame;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel problemIDLabel;
    private javax.swing.JLabel problemLevelLabel;
    private javax.swing.JTextArea problemStatementTextArea;
    private javax.swing.JLabel problemTitleLabel;
    private javax.swing.JFrame problemsFrame;
    private javax.swing.JButton profileActionButton;
    private javax.swing.JFrame profileFrame;
    private javax.swing.JFrame requests;
    private javax.swing.JFrame searchFrame;
    private javax.swing.JButton showCurrentContestsButton;
    private javax.swing.JButton showPreviousContestsButton;
    private javax.swing.JButton signInButton;
    private javax.swing.JButton signUpButton;
    private javax.swing.JFrame solveProblemFrame;
    private javax.swing.JButton standingsButton;
    private javax.swing.JFrame standingsFrame;
    private javax.swing.JButton submitCodeButton;
    // End of variables declaration//GEN-END:variables

}
